// frontend/src/components/schedule-view/AssignmentBox.svelte
<script lang=typescript>

    import type { Assignment } from '../../openapi'
    import { ShiftType } from '../../openapi'

    export let assignment: Assignment
    export let free_day: boolean

    function getColor(st: ShiftType): string {
        switch (st) {
            case ShiftType.JAEV:
                return "bg-yellow-400";
            case ShiftType.SANW:
                return "bg-green-400";
            case ShiftType.JAWE:
                return "bg-red-500";
            case ShiftType.JAHO:
                return "bg-blue-500";
            case ShiftType.SAEW:
                return "bg-green-500";
            case ShiftType.SAWE:
                return "bg-red-600";
            case ShiftType.SAHO:
                return "bg-blue-600";
            case ShiftType.CALL:
                return "bg-green-600";
            case ShiftType.TPWE:
                return "bg-red-700";
            case ShiftType.TPHO:
                return "bg-blue-700";
            case ShiftType.FREE:
                if (free_day) return "bg-gray-200";
                return "bg-gray-100";
        }
    }

</script>

<main>
    {#if assignment.part_of_min_balance && assignment.shift_type == ShiftType.FREE}
        <div class="flex flex-none w-12 h-6 rounded-lg justify-center items-center cursor-default {free_day ? " bg-gray-200" : " bg-gray-100"}">
            <div class="text-xs text-red-500 font-bold"> ! </div>
        </div>
    {:else}
        <div class="flex flex-none w-12 h-6 {getColor(assignment.shift_type)} rounded-lg justify-center items-center cursor-default">
            <div class="text-xs font-bold text-white"> {assignment.shift_type}</div>
        </div>
    {/if}
</main>

// frontend2/src/app/schedule_view/assignment-box/assignment-box.component.ts
import { Component, OnInit, Input } from '@angular/core';


import type { Assignment, ModelParameters } from "build/openapi";

import { ShiftType } from 'build/openapi';

import { DefaultService } from 'build/openapi';


export let free_day: boolean

@Component({
  selector: 'app-assignment-box',
  templateUrl: './assignment-box.component.html',
  styleUrls: ['./assignment-box.component.css'],
  providers: [ DefaultService ]
})
export class AssignmentBoxComponent implements OnInit {

  modelParameters: ModelParameters;


  @Input()
  assignment: Assignment;

  

  constructor(private modelParamService: DefaultService) { }
  ngOnInit(): void {
    //this.getShiftTypes();

  }

  getColor(st: ShiftType): string {
    switch (st) {
      case ShiftType.Jaev:
          return "bg-yellow-400";
      case ShiftType.Sanw:
          return "bg-green-400";
      case ShiftType.Jawe:
          return "bg-red-500";
      case ShiftType.Jaho:
          return "bg-blue-500";
      case ShiftType.Saew:
          return "bg-green-500";
      case ShiftType.Sawe:
          return "bg-red-600";
      case ShiftType.Saho:
          return "bg-blue-600";
      case ShiftType.Call:
          return "bg-green-600";
      case ShiftType.Tpwe:
          return "bg-red-700";
      case ShiftType.Tpho:
          return "bg-blue-700";
      case ShiftType.Free:
          if (free_day) return "bg-gray-200";
          return "bg-gray-100";
  }
  return "";
}
  
  getShiftTypes(): void {
  
    this.modelParamService.modelParametersGetGet().subscribe(modelParameters => (this.modelParameters = modelParameters));
  }

}

<div class="assignment-box-button">
    
   <!--
    <div *ngFor="let item of modelParameters.shift_type_parameters"
     class="flex flex-none w-12 h-6 {{getColor(item.shift_type)}} rounded-lg justify-center items-center cursor-default"
      >  
     <div class="text-xs font-bold text-white"> {{item.shift_type}}</div>

   --> 
     <div class="flex flex-none w-12 h-6 {{getColor(assignment.shift_type)}} rounded-lg justify-center items-center cursor-default">
        <div class="text-xs font-bold text-white"> {{assignment.shift_type}}</div>
    </div>
    
</div>
