// frontend/src/components/model-input/Button.svelte

<script lang=typescript>

    export let callback: () => void
    export let primary: boolean = true
    
</script>

{#if primary}
    <button on:click={callback} type="button" class="bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded text-xs focus:outline-none border-transparent">
        <slot/>
    </button>
{:else}
    <button on:click={callback} type="button" class="hover:bg-gray-100 text-green-500 font-bold py-1 px-2 rounded text-xs focus:outline-none border-transparent">
        <slot/>
    </button>
{/if}

// frontend2/src/app/model_input/button/button.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.css']
})
export class ButtonComponent implements OnInit {
  
  @Input()
  callback(): void {};

  @Input()
  buttonText: string;
  
  hello: string = "button";
  primary: boolean = true

  constructor() { }



  ngOnInit(): void {
  }

}



<button type="button" (click)="callback()" class="bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded text-xs focus:outline-none border-transparent">
    {{buttonText}}
</button>
