// frontend2/src/app/instance_input/assistant-input/assistant-input.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import {MatDialog} from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatFormField } from '@angular/material/form-field';


import { InstanceData, Assistant, Service } from "build/openapi";
import { AssistantType } from "build/openapi";

import { IconButtonComponent } from "../../model_input/icon-button/icon-button.component"
import { ButtonComponent } from "../../model_input/button/button.component";
//import Modal from "../Modal.svelte";
import { DayHeaderComponent } from "../../schedule_view/day-header/day-header.component";
import { NewAssistantComponent } from "../new-assistant/new-assistant.component";




@Component({
  selector: 'app-assistant-input',
  templateUrl: './assistant-input.component.html',
  styleUrls: ['./assistant-input.component.css']
})
export class AssistantInputComponent implements OnInit {

  @Input()
  data?: InstanceData;
  assistantTypes: AssistantType[] = Object.values(AssistantType);

  id_array = this.data?.assistants.map((a) => a.id)

  new_assistant: Assistant = {
    id: this.id_array?.reduce(function (a, b) {
      return Math.max(a, b);
    }, 0) + 1,
    name: "",
    type: AssistantType.Ja,
    free_days: []
  }

  removeAssistant(assistant: Assistant): void {
    
    this.data.assistants = this.data.assistants.filter((a) => a.id != assistant.id)
  }

  addAssistant(): void {
    this.data.assistants.push(this.new_assistant)
    this.new_assistant = {
      id: this.id_array?.reduce(function (a, b) {
        return Math.max(a, b);
      }, 0) + 1,
      name: "",
      type: AssistantType.Ja,
      free_days: []
    }

    this.data.assistants = this.data.assistants
  }

  toggle(assistant: Assistant, day_nb: number): void {
    if (assistant.free_days.includes(day_nb)) {
      assistant.free_days = assistant.free_days.filter((d: number) => d != day_nb)
    } else {
      assistant.free_days.push(day_nb)
    }
    this.data.assistants = this.data.assistants
  }
  /*
  setWeek(assistant: Assistant, weekNb: number, selected: any): void {
    if (selected.checked) {
      [7 * weekNb + 1, 7 * weekNb + 2, 7 * weekNb + 3, 7 * weekNb + 4, 7 * weekNb + 5, 7 * weekNb + 6, 7 * weekNb + 7]
        .forEach((day) => {
          if (!assistant.free_days.includes(day)) assistant.free_days.push(day)
        })
    } else {
      [7 * weekNb + 1, 7 * weekNb + 2, 7 * weekNb + 3, 7 * weekNb + 4, 7 * weekNb + 5, 7 * weekNb + 6, 7 * weekNb + 7]
        .forEach((day) => {
          assistant.free_days = assistant.free_days.filter((d: number) => d != day)
        })
    }
    this.data.assistants = this.data.assistants
  } */

  freeWeek(assistant: Assistant, weekNb: number): boolean {
    return [7 * weekNb + 1, 7 * weekNb + 2, 7 * weekNb + 3, 7 * weekNb + 4, 7 * weekNb + 5, 7 * weekNb + 6, 7 * weekNb + 7]
      .every((day) => assistant.free_days.includes(day))
  }

  getTypeString(type: AssistantType): string {
    switch (type) {
      case AssistantType.Ja: return "JA"
      case AssistantType.JaF: return "JA_F"
      case AssistantType.Sa: return "SA"
      case AssistantType.SaF: return "SA_F"
      case AssistantType.SaNeo: return "SA_N"
      case AssistantType.SaFNeo: return "SA_FN"
    }
    return ""
  }

  changeNewAssistantName(newName: string){
    this.new_assistant.name = newName;
  }

  constructor(public dialog: MatDialog) {}

  openDialog() {
    const dialogRef = this.dialog.open(AssistantInputDialogContent);
    dialogRef.componentInstance.data = this.data
    dialogRef.afterClosed().subscribe(result => {
      if(result){
        this.handleSubmit();
      }
    });
  }


  ngOnInit(): void {
    console.log("init assistant input")
    console.log("data: ", this.data)
    let isSyncingLeftScroll: boolean = false;
    let isSyncingTopScroll: boolean = false;
    let isSyncingCenterScroll: boolean = false;
    let leftDiv: HTMLElement = document.getElementById('left');
    let topDiv: HTMLElement = document.getElementById('top');
    let centerDiv: HTMLElement = document.getElementById('center');

    /*
    leftDiv.onscroll = function () {
      if (!isSyncingLeftScroll) {
        isSyncingCenterScroll = true;
        centerDiv.scrollTop = leftDiv.scrollTop;
      }
      isSyncingLeftScroll = false;
    }

    topDiv.onscroll = function () {
      if (!isSyncingTopScroll) {
        isSyncingCenterScroll = true;
        centerDiv.scrollLeft = topDiv.scrollLeft;
      }
      isSyncingTopScroll = false;
    }

    centerDiv.onscroll = function () {
      if (!isSyncingCenterScroll) {
        isSyncingLeftScroll = true;
        isSyncingTopScroll = true;
        leftDiv.scrollTop = centerDiv.scrollTop;
        topDiv.scrollLeft = centerDiv.scrollLeft;
      }
      isSyncingCenterScroll = false;

    } */
  }
  /*
  openWindow(): void {
    open()
  }

  closeWindow(): void {
    close()
  } 

  addAndClose(): void {
    this.addAssistant()
    close()
  } */
  handleSubmit(): void {
    Service.postInstanceData(this.data)
  }
}

@Component({
  selector: 'assistant-input-dialog-content',
  templateUrl: 'assistant-input-dialog-content.html',
  providers: [ Service]
})
export class AssistantInputDialogContent implements OnInit {

  constructor(public dialog: MatDialog) {}

  data?: InstanceData;
  assistantTypes: AssistantType[] = Object.values(AssistantType);

  id_array = this.data?.assistants.map((a) => a.id)

  new_assistant: Assistant = {
    id: this.id_array?.reduce(function (a, b) {
      return Math.max(a, b);
    }, 0) + 1,
    name: "",
    type: AssistantType.Ja,
    free_days: []
  }

  removeAssistant(assistant: Assistant): void {
    this.data.assistants = this.data.assistants.filter((a) => a.id != assistant.id)
  }

  addAssistant(): void {
  
    this.data.assistants.push(this.new_assistant)
    this.new_assistant = {
      id: this.id_array?.reduce(function (a, b) {
        return Math.max(a, b);
      }, 0) + 1,
      name: "",
      type: AssistantType.Ja,
      free_days: []
    }

    this.data.assistants = this.data.assistants
  }

  toggle(assistant: Assistant, day_nb: number): void {

    if (assistant.free_days.includes(day_nb)) {
      assistant.free_days = assistant.free_days.filter((d: number) => d != day_nb)
    } else {
      assistant.free_days.push(day_nb)
    }
    //this.data.assistants = this.data.assistants
  }

  setWeek(assistant: Assistant, weekNb: number, selected: any): void {
    console.log("SET WEEK: ", selected)
    if (selected.checked) {
      [7 * weekNb + 1, 7 * weekNb + 2, 7 * weekNb + 3, 7 * weekNb + 4, 7 * weekNb + 5, 7 * weekNb + 6, 7 * weekNb + 7]
        .forEach((day) => {
          if (!assistant.free_days.includes(day)) assistant.free_days.push(day)
        })
    } else {
      [7 * weekNb + 1, 7 * weekNb + 2, 7 * weekNb + 3, 7 * weekNb + 4, 7 * weekNb + 5, 7 * weekNb + 6, 7 * weekNb + 7]
        .forEach((day) => {
          assistant.free_days = assistant.free_days.filter((d: number) => d != day)
        })
    }
    this.data.assistants = this.data.assistants
  }

  freeWeek(assistant: Assistant, weekNb: number): boolean {
    return [7 * weekNb + 1, 7 * weekNb + 2, 7 * weekNb + 3, 7 * weekNb + 4, 7 * weekNb + 5, 7 * weekNb + 6, 7 * weekNb + 7]
      .every((day) => assistant.free_days.includes(day))
  }

  getTypeString(type: AssistantType): string {
    switch (type) {
      case AssistantType.Ja: return "JA"
      case AssistantType.JaF: return "JA_F"
      case AssistantType.Sa: return "SA"
      case AssistantType.SaF: return "SA_F"
      case AssistantType.SaNeo: return "SA_N"
      case AssistantType.SaFNeo: return "SA_FN"
    }
    return ""
  }

  changeNewAssistantName(newName: string){
    this.new_assistant.name = newName;
  }

  ngOnInit(): void {
    console.log("init assistant input")
    console.log("data: ", this.data)
    let isSyncingLeftScroll: boolean = false;
    let isSyncingTopScroll: boolean = false;
    let isSyncingCenterScroll: boolean = false;
    let leftDiv: HTMLElement = document.getElementById('left');
    let topDiv: HTMLElement = document.getElementById('top');
    let centerDiv: HTMLElement = document.getElementById('center');
    
    leftDiv.onscroll = function () {
      if (!isSyncingLeftScroll) {
        isSyncingCenterScroll = true;
        centerDiv.scrollTop = leftDiv.scrollTop;
      }
      isSyncingLeftScroll = false;
    }

    topDiv.onscroll = function () {
      if (!isSyncingTopScroll) {
        isSyncingCenterScroll = true;
        centerDiv.scrollLeft = topDiv.scrollLeft;
      }
      isSyncingTopScroll = false;
    }

    centerDiv.onscroll = function () {
      if (!isSyncingCenterScroll) {
        isSyncingLeftScroll = true;
        isSyncingTopScroll = true;
        leftDiv.scrollTop = centerDiv.scrollTop;
        topDiv.scrollLeft = centerDiv.scrollLeft;
      }
      isSyncingCenterScroll = false;

    } 
  }
  /*
  closeWindow(): void {
    close()
  }

  addAndClose(): void {
    this.addAssistant()
    close()
  } */

  handleSubmit(): void {
    console.log("POST INSTANCE DATA")
    console.log("Data:", this.data)
    
  
    Service.postInstanceData(this.data)
  }

  openDialog() {
    this.id_array= this.data?.assistants.map((a) => a.id)
    this.new_assistant.id = this.id_array?.reduce(function (a, b) {
      return Math.max(a, b);
    }, 0) + 1
    console.log("id_array: ", this.id_array)
    console.log("data: ", this.data)
    const dialogRef = this.dialog.open(NewAssistantDialogComponent);
    dialogRef.componentInstance.assistantTypes = this.assistantTypes;
    dialogRef.afterClosed().subscribe(result => {
      console.log(`Dialog result: ${result}`);
      console.log("name: ", dialogRef.componentInstance.value);
      console.log("type: ", dialogRef.componentInstance.assistantType);
      if(result){
        console.log("id: ", this.new_assistant.id)
        console.log("type: ", this.new_assistant.type)
        this.changeNewAssistantName(dialogRef.componentInstance.value);
        this.new_assistant.type = dialogRef.componentInstance.assistantType;
        this.addAssistant();
        this.handleSubmit();
      }
    });
    
  }

  

}



@Component({
  selector: 'app-new-assistant-dialog',
  templateUrl: './new-assistant-dialog.component.html',
  styleUrls: ['./new-assistant-dialog.component.css']
})
export class NewAssistantDialogComponent implements OnInit {


  assistantName: string;
  assistantType: AssistantType;
  assistantTypes: AssistantType[] = Object.values(AssistantType);

  @Input()
  value: string;

  @Output()
  onAssistantNameChange = new EventEmitter<string>();


  @Output()
  onAssistantTypeChange = new EventEmitter<AssistantType>();

  assistantNameChanged(newAssistantName: string){

    this.value = newAssistantName;
    this.onAssistantNameChange.emit(newAssistantName);
  }

  assistantTypeChanged(newAssistantTypeString: string){
    console.log(newAssistantTypeString)
    const newAssistantType = this.getStringType(newAssistantTypeString);
    this.assistantType = this.getStringType(newAssistantTypeString);


    this.onAssistantTypeChange.emit(this.getStringType(newAssistantTypeString));

    
  }


  getStringType(typeString: string): AssistantType {
    switch (typeString) {
      case "JA": return AssistantType.Ja
      case "JA_F": return AssistantType.JaF
      case "SA": return AssistantType.Sa
      case "SA_F": return AssistantType.SaF
      case "SA_NEO": return AssistantType.SaNeo
      case "SA_F_NEO": return AssistantType.SaFNeo
    }
    return AssistantType.Ja
  }

  constructor() { }

  ngOnInit(): void {
  }

}



    <!-- 
<div class="grid grid-cols-12" style="height: 70vh; width: 180vw">
    <div class="flex-none mb-2 col-span-3">
        --><!-- <Modal> --><!-- 
        <div slot="trigger" let:open>
            <app-button buttonText=New (callback)="openWindow()">  </app-button>
        </div>
        <div class="my-2" slot="header">
            <h1 class="font-bold"> New assistant </h1>
        </div>
        <div class="my-2" slot="content">
            <app-new-assistant [value]="new_assistant.name" (onAssistantNameChange)="changeNewAssistantName($event)">
            </app-new-assistant>
        </div>
        <div class="my-5 flex flex-row justify-end space-x-2" slot="footer" let:close>
            <app-button buttonText=Close (callback)=closeWindow()> </app-button>
            <app-button buttonText=Create (callback)="addAndClose()">  </app-button>
        </div>
    --><!-- </Modal> --><!-- 
    </div>

-->
<!--

    <div id="top" class="scrollbar-hidden flex flex-row col-span-9 space-x-1 overflow-auto">

        <div *ngFor="let day of data.days">
            <div *ngIf="day.id % 7 === 1;else notFriday">
                <div class="flex flex-none w-8">
                    <app-day-header [day]=day></app-day-header>
                </div>
            </div>
            <ng-template #notFriday>
                <app-day-header [day]=day></app-day-header>
            </ng-template>

        </div>
    </div>

    <div id="left" class="scrollbar-hidden flex flex-col space-y-1 col-span-3 overflow-auto">
        <div *ngFor="let type of assistantTypes">
            <div *ngFor="let assistant of data.assistants">
                <div *ngIf="assistant.type == type">
                    <div class="p-2 flex-none flex h-6 flex-row w-full justify-between">
                        <app-icon-button (callback)=removeAssistant(assistant)>
                            <span class=" h-4 w-8 color-gray-500 iconify" data-icon="ic:round-remove-circle-outline"
                                data-inline="false">
                            </span>
                        </app-icon-button>
                        <p class="w-10 text-black text-xs"> {{getTypeString(assistant.type)}} </p>
                        <p class="font-bold w-24 h-6 text-black text-xs text-right truncate"> {{assistant.name}} </p>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


<div id="center" class="scrollable flex flex-col col-span-9 space-y-1 overflow-auto">

    <div *ngFor="let type of assistantTypes">
        <div *ngFor="let assistant of data.assistants">
            <div *ngIf="assistant.type == type">

                <div class="flex flex-row space-x-1">

                    <div *ngFor="let day of data.days">
                        <div *ngIf="day.id % 7 === 1">

                            <div class="flex w-8 justify-items-end items-center">
                                <input #freeWeekInput type="checkbox" checked="freeWeek(assistant, (day.id-1)/7)"
                                    class="ml-4 w-4 text-xs text-black font-bold" (change)="setWeek(assistant, (day.id-1)/7, freeWeekInput.checked)"/>
                            </div>


                        </div>
                        <div (click)="toggle(assistant, day.id)"
                            class="flex-none w-12 h-6 bg-yellow-400 rounded cursor-pointer flex justify-center items-center">
                            <div class="text-xs text-white font-bold"> FREE </div>
                        </div>

                    </div>
                </div>



            </div>
        </div>
    </div>
    <app-button buttonText="-" (click)=removeWeek()> </app-button>

</div>
-->

<div class="my-2" slot="header" (click)=openDialog()>
    
    <button mat-raised-button color="primary">Edit assistants</button>
</div>
<div class="my-2" slot="content">
    <!-- <app-assistant-input-dialog-content [data]=data></app-assistant-input-dialog-content> -->
</div>

// frontend/src/components/instance-input/AssistantInput.svelte

<script lang=typescript>

    import type { InstanceData, Assistant } from "../../openapi";
    import { AssistantType } from "../../openapi";

    import IconButton from "../model-input/IconButton.svelte";
    import Button from "../model-input/Button.svelte";
    import Modal from "../Modal.svelte";
    import DayHeader from "../schedule-view/DayHeader.svelte";
    import NewAssistant from "./NewAssistant.svelte";

    import { onMount } from 'svelte';

    onMount(async () => {
		let isSyncingLeftScroll: boolean = false;
        let isSyncingTopScroll: boolean = false;
        let isSyncingCenterScroll: boolean = false;
        let leftDiv: HTMLElement = document.getElementById('left');
        let topDiv: HTMLElement = document.getElementById('top');
        let centerDiv: HTMLElement = document.getElementById('center');

        leftDiv.onscroll = function() {
            if (!isSyncingLeftScroll) {
                isSyncingCenterScroll = true;
                centerDiv.scrollTop = leftDiv.scrollTop;
            }
            isSyncingLeftScroll = false;
        }

        topDiv.onscroll = function() {
            if (!isSyncingTopScroll) {
                isSyncingCenterScroll = true;
                centerDiv.scrollLeft = topDiv.scrollLeft;
            }
            isSyncingTopScroll = false;
        }

        centerDiv.onscroll = function() {
            if (!isSyncingCenterScroll) {
                isSyncingLeftScroll = true;
                isSyncingTopScroll = true;
                leftDiv.scrollTop = centerDiv.scrollTop;
                topDiv.scrollLeft = centerDiv.scrollLeft;
            }
            isSyncingCenterScroll = false;

        }
	});

    export let data: InstanceData;

    const types: AssistantType[] = Object.values(AssistantType)

    let new_assistant: Assistant = {
        id: Math.max(...data.assistants.map((a) => a.id)) + 1,
        name: "",
        type: AssistantType.JA,
        free_days: []
    }

    function removeAssistant(assistant: Assistant) {
        data.assistants = data.assistants.filter((a) => a.id != assistant.id)
    }

    function addAssistant() {
        data.assistants.push(new_assistant)
        new_assistant = {
            id: Math.max(...data.assistants.map((a) => a.id)) + 1,
            name: "",
            type: AssistantType.JA,
            free_days: []
        }

        data.assistants = data.assistants
    }

    function toggle(assistant: Assistant, day_nb: number) {
        if (assistant.free_days.includes(day_nb)) {
            assistant.free_days = assistant.free_days.filter((d: number) => d != day_nb)
        } else {
            assistant.free_days.push(day_nb)
        }
        data.assistants = data.assistants
    }

    function setWeek(assistant: Assistant, weekNb: number, selected: boolean) {
        if (selected) {
            [7*weekNb+1, 7*weekNb+2, 7*weekNb+3, 7*weekNb+4, 7*weekNb+5, 7*weekNb+6, 7*weekNb+7]
                .forEach((day) => {
                    if (!assistant.free_days.includes(day)) assistant.free_days.push(day)
                })
        } else {
            [7*weekNb+1, 7*weekNb+2, 7*weekNb+3, 7*weekNb+4, 7*weekNb+5, 7*weekNb+6, 7*weekNb+7]
                .forEach((day) => {
                    assistant.free_days = assistant.free_days.filter((d: number) => d != day) 
                })   
        }
        data.assistants = data.assistants 
    }

    function freeWeek(assistant: Assistant, weekNb: number) {
        return [7*weekNb+1, 7*weekNb+2, 7*weekNb+3, 7*weekNb+4, 7*weekNb+5, 7*weekNb+6, 7*weekNb+7]
            .every((day) => assistant.free_days.includes(day))
    }

    function getTypeString(type: AssistantType): string {
        switch (type) {
            case AssistantType.JA: return "JA"
            case AssistantType.JA_F: return "JA_F"
            case AssistantType.SA: return "SA"
            case AssistantType.SA_F: return "SA_F"
            case AssistantType.SA_NEO: return "SA_N"
            case AssistantType.SA_F_NEO: return "SA_FN"
        }
    }
</script>


<div class="grid grid-cols-12" style="height: 70vh; width: 80vw">
    <div class="flex-none mb-2 col-span-3">
        <Modal>
            <div slot="trigger" let:open>
                <Button callback={open}> New </Button>
            </div>
            <div class="my-2" slot="header">
                <h1 class="font-bold"> New assistant </h1>
            </div>
            <div class="my-2" slot="content">
                <NewAssistant bind:assistant={new_assistant}/>
            </div>
            <div class="my-5 flex flex-row justify-end space-x-2" slot="footer" let:close>
                <Button primary={false} callback={close}> Close </Button>
                <Button callback={() => {addAssistant(); close()}}> Create </Button>
            </div>
        </Modal>
    </div>
    <div id="top" class="scrollbar-hidden flex flex-row col-span-9 space-x-1 overflow-auto">
        {#each data.days as day}
            {#if day.id % 7 === 1}
                <!-- placeholder -->
                <div class="flex flex-none w-8"/>
            {/if}
            <DayHeader {day}/>
        {/each}
    </div>
    <div id="left" class="scrollbar-hidden flex flex-col space-y-1 col-span-3 overflow-auto">
        {#each types as type}
            {#each data.assistants.filter((a) => a.type == type) as assistant (assistant.id)}
                <div class="p-2 flex-none flex h-6 flex-row w-full justify-between">
                    <IconButton callback={() => removeAssistant(assistant)}>
                        <span class="h-4 w-8 color-gray-500 iconify" 
                            data-icon="ic:round-remove-circle-outline" 
                            data-inline="false"/>
                    </IconButton>
                    <p class="w-10 text-black text-xs"> {getTypeString(assistant.type)} </p>
                    <p class="font-bold w-24 h-6 text-black text-xs text-right truncate"> {assistant.name} </p>
                </div>   
            {/each}
        {/each}
    </div>
    <div id="center" class="scrollable flex flex-col col-span-9 space-y-1 overflow-auto">
        {#each types as type}
            {#each data.assistants.filter((a) => a.type == type) as assistant (assistant.id)}
                <div class="flex flex-row space-x-1">
                    {#each data.days as day}
                        {#if day.id % 7 === 1}
                        <div class="flex w-8 justify-items-end items-center">
                            <input type="checkbox" checked={freeWeek(assistant, (day.id-1)/7)} class="ml-4 w-4 text-xs text-black font-bold" on:change={e => setWeek(assistant, (day.id-1)/7, e.target.checked)}/>
                        </div>
                        {/if}
                        <div on:click={() => toggle(assistant, day.id)} class="flex-none w-12 h-6 {assistant.free_days.includes(day.id) ? "bg-yellow-400" : "bg-gray-100"} rounded cursor-pointer flex justify-center items-center">
                            <div class="text-xs text-white font-bold"> FREE </div>
                        </div>
                    {/each}
                </div>
            {/each}
        {/each}
    </div>
</div>
