// frontend2/src/app/instance_input/date-picker/date-picker.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';

//import Modal from "../Modal.svelte"
import { ButtonComponent } from "../../model_input/button/button.component"
import { DayHeaderComponent } from "../../schedule_view/day-header/day-header.component";





@Component({
  selector: 'app-date-picker',
  templateUrl: './date-picker.component.html',
  styleUrls: ['./date-picker.component.css']
})
export class DatePickerComponent implements OnInit {



  constructor(public dialog: MatDialog) {}

  @Output()
  dateChanged = new EventEmitter<{day: number, month: number, year: number}>();



  openDialog() {
    const dialogRef = this.dialog.open(EditDateDialogContent);
    dialogRef.componentInstance.currentDate = this.currentDate;
    dialogRef.componentInstance.visibleMonth = this.currentDate.month
    dialogRef.componentInstance.visibleYear = this.currentDate.year
    dialogRef.componentInstance.updateMonthDays();
    dialogRef.afterClosed().subscribe(result => {
      
      if(result){
        this.currentDate = dialogRef.componentInstance.currentDate; // TODO: wss nog wel moeten resetten anders in dialog bij close
        this.dateChanged.emit(this.currentDate);
      }
    });
  
  }


  @Input()
  currentDate?: {day: number, month: number, year: number};
  
  @Input()
  handleSubmit: VoidFunction;

  
  setStartDate: (date: Date) => void;

  visibleMonth = this.currentDate?.month
  visibleYear = this.currentDate?.year
  blankDays: Date[];
  monthDays: Date[];


  DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

  updateMonthDays(): void {
    this.blankDays = Array((new Date(this.visibleYear, this.visibleMonth-1).getDay()+6) % 7);
    this.monthDays = new Array(31)
      .fill('')
      .map((_,i) => new Date(this.visibleYear,this.visibleMonth-1,i+1))
      .filter((v) => v.getMonth() === this.visibleMonth-1)
  }

  setStartDay(date: Date){
    
    this.currentDate = {
      day: date.getDate(),
      month: date.getMonth() + 1,
      year: date.getFullYear()
    }
  }

  incrementMonth(): void {
    if (this.visibleMonth == 12) {
      this.visibleMonth = 1
      this.visibleYear++
    } else {
      this.visibleMonth++
    }
    this.updateMonthDays()
  }
  
  decrementMonth(): void {
    if (this.visibleMonth == 1) {
      this.visibleMonth = 12;
      this.visibleYear--
    } else {
      this.visibleMonth--
    }
    this.updateMonthDays()
  }

  resetStateAnd(callback: VoidFunction): void {
    this.visibleMonth = this.currentDate.month
    this.visibleYear = this.currentDate.year
    this.updateMonthDays()
    callback()
  }

  closeWindow(): void {
    close()
  }

  openWindow(): VoidFunction {
    return open;
  }

  closeAndSubmit(): void {
    this.handleSubmit()
    close()
  }

  dateToValue(): string {
    const returnDate = new Date(this.currentDate.year, this.currentDate.month-1, this.currentDate.day)
    console.log()
    return returnDate.toDateString()
  }



  ngOnInit(): void {
    this.visibleMonth = this.currentDate.month
    this.visibleYear = this.currentDate.year
    this.updateMonthDays()
    console.log("DATE PICKER INITIALIZED")
  }

}





@Component({
  selector: 'edit-date-dialog-content',
  templateUrl: './edit-date-dialog-content.html',
})
export class EditDateDialogContent {
  constructor() {}
  


  @Input()
  currentDate?: {day: number, month: number, year: number};
  
  @Input()
  handleSubmit: VoidFunction;

  
  setStartDate: (date: Date) => void;

  visibleMonth = this.currentDate?.month
  visibleYear = this.currentDate?.year
  blankDays: Date[];
  monthDays: Date[];


  DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

  updateMonthDays(): void {
  
    this.blankDays = Array((new Date(this.visibleYear, this.visibleMonth-1).getDay()+6) % 7);
    this.monthDays = new Array(31)
      .fill('')
      .map((_,i) => new Date(this.visibleYear,this.visibleMonth-1,i+1))
      .filter((v) => v.getMonth() === this.visibleMonth-1)
  }

  setStartDay(date: Date){
    console.log("SET START DAY!!")
    console.log(date)
    console.log("day: ", date.getDate())
    console.log("month: ", date.getMonth())
    console.log("year: ", date.getFullYear())
    this.currentDate = {
      day: date.getDate(),
      month: date.getMonth(),
      year: date.getFullYear()
    }
  }

  incrementMonth(): void {
    console.log("CURRENT DATE: ", this.currentDate)
    if (this.visibleMonth == 12) {
      this.visibleMonth = 1
      this.visibleYear++
    } else {
      this.visibleMonth++
    }
    this.updateMonthDays()
  }
  
  decrementMonth(): void {
    if (this.visibleMonth == 1) {
      this.visibleMonth = 12;
      this.visibleYear--
    } else {
      this.visibleMonth--
    }
    this.updateMonthDays()
  }

  resetStateAnd(callback: VoidFunction): void {
    this.visibleMonth = this.currentDate.month
    this.visibleYear = this.currentDate.year
    this.updateMonthDays()
    callback()
  }

  closeWindow(): void {
    close()
  }

  openWindow(): VoidFunction {
    return open;
  }

  closeAndSubmit(): void {
    this.handleSubmit()
    close()
  }

  dateToValue(): string {
    const returnDate = new Date(this.currentDate.year, this.currentDate.month-1, this.currentDate.day)
    console.log()
    return returnDate.toDateString()
  }






}


<div class="relative mt-2" slot="trigger" let:open (click)=openDialog()>
    <input
        class="p-2 w-full leading-none rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium text-xs"
        type="text" value={{dateToValue()}} readonly placeholder="Select date">

    <div class="absolute top-0 right-0 p-1.5">
        <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
    </div>
</div>


<!-- TODO dit deel hieronder-->
<!--
<div class="relative mt-4" slot="trigger" let:open (click)=resetStateAnd(openWindow())>
    <input
        class="p-2 w-full leading-none rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium text-xs"
        type="text" value={{dateToValue()}} readonly placeholder="Select date">

    <div class="absolute top-0 right-0 p-1.5">
        <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
    </div>
</div>

-->

// frontend/src/components/instance-input/DatePicker.svelte
<script lang=typescript>
  import Modal from "../Modal.svelte"
  import Button from "../model-input/Button.svelte"
import DayHeader from "../schedule-view/DayHeader.svelte";

  export let currentDate: {day: number, month: number, year: number};
  export let handleSubmit: VoidFunction;
  export let setStartDate: (date: Date) => void;

  let visibleMonth = currentDate.month
  let visibleYear = currentDate.year
  let blankDays: Date[];
  let monthDays: Date[];

  const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  function updateMonthDays() {
    blankDays = Array((new Date(visibleYear, visibleMonth-1).getDay()+6) % 7);
    monthDays = new Array(31)
      .fill('')
      .map((_,i) => new Date(visibleYear,visibleMonth-1,i+1))
      .filter((v) => v.getMonth() === visibleMonth-1)
  }

  function incrementMonth() {
    if (visibleMonth == 12) {
      visibleMonth = 1
      visibleYear++
    } else {
      visibleMonth++
    }
    updateMonthDays()
  }
    

  function decrementMonth() {
    if (visibleMonth == 1) {
      visibleMonth = 12;
      visibleYear--
    } else {
      visibleMonth--
    }
    updateMonthDays()
  }

  updateMonthDays()

  function resetStateAnd(callback: VoidFunction) {
    visibleMonth = currentDate.month
    visibleYear = currentDate.year
    updateMonthDays()
    callback()
  }

</script>


<Modal>
  <div class="relative mt-4" slot="trigger" let:open  on:click={() => resetStateAnd(open)}> 
    <input 
    class="p-2 w-full leading-none rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium text-xs"
    type="text"
    value={new Date(currentDate.year, currentDate.month-1, currentDate.day).toDateString()}
    readonly
    placeholder="Select date">

    <div class="absolute top-0 right-0 p-1.5">
      <svg class="h-5 w-5 text-gray-400"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
      </svg>
    </div>
  </div>

  <div class="my-2" slot="header">
      <h1 class="font-bold"> Select start date </h1>
  </div>

  <div slot="content" class="w-64 h-72 bg-white m-6 rounded-lg border border-black p-4">
    <div class="flex justify-between items-center">
      <div>
        <span class="text-lg font-bold text-gray-800"> {MONTH_NAMES[visibleMonth-1]}</span>
        <span class="ml-1 text-lg text-gray-600 font-normal"> {visibleYear}</span>
      </div>
      <div>
        <div 
          type="button"
          class="inline-flex cursor-pointer hover:bg-gray-200 p-1 rounded-full" 
          on:click={() => decrementMonth()}>
          <svg class="h-6 w-6 text-gray-500 inline-flex"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
          </svg>  
        </div>
        <div 
          type="button"
          class="inline-flex cursor-pointer hover:bg-gray-200 p-1 rounded-full" 
          on:click={() => incrementMonth()}>
          <svg class="h-6 w-6 text-gray-500 inline-flex"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
          </svg>									  
        </div>
      </div>
    </div>

    <div class="flex flex-wrap my-3 -mx-1">
      {#each DAYS as day}
        <div style="width: 14.26%" class="px-1">
          <div class="text-gray-800 font-medium text-center text-xs"> {day} </div>
        </div>
      {/each}
    </div>

    <div class="flex flex-wrap -mx-1">
      {#each blankDays as _}
        <div style="width: 14.28%"/>
      {/each}
      {#each monthDays as day}
        <div style="width: 14.28%" class="px-0.5 mb-1">
          {#if day.getDay() == 5}
            <div 
              class={"cursor-pointer leading-loose text-center text-sm rounded-full font-bold " + 
                      (currentDate.year === day.getFullYear()
                        && currentDate.month-1 === day.getMonth()
                        && currentDate.day === day.getDate() 
                      ? "bg-green-500 text-white" 
                      : "text-gray-700 hover:bg-green-300")
                    }
              on:click={() => setStartDate(day)}
            >
              {day.getDate()}
            </div>   
          {:else}
            <div class={"leading-loose text-center text-sm rounded-full text-gray-500 font-normal"}>     
              {day.getDate()}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  </div>

  <div class="my-5 flex flex-row justify-end space-x-2" slot="footer" let:close>
      <Button primary={false} callback={close}> Close </Button>
      <Button callback={() => {handleSubmit(); close()}}> Submit </Button>
  </div>
</Modal>
