// frontend2/src/app/instance_input/new-assistant/new-assistant.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

import type { Assistant } from "build/openapi";
import { AssistantType } from "build/openapi";




@Component({
  selector: 'app-new-assistant',
  templateUrl: './new-assistant.component.html',
  styleUrls: ['./new-assistant.component.css']
})
export class NewAssistantComponent implements OnInit {


  assistantName: string;
  assistantType: AssistantType;
  assistantTypes: AssistantType[] = Object.values(AssistantType);

  @Input()
  value: string;

  @Output()
  onAssistantNameChange = new EventEmitter<string>();


  @Output()
  onAssistantTypeChange = new EventEmitter<AssistantType>();

  assistantNameChanged(newAssistantName: string){
    this.onAssistantNameChange.emit(newAssistantName);
  }

  assistantTypeChanged(newAssistantTypeString: string){
    const newAssistantType = this.getStringType(newAssistantTypeString);
    this.onAssistantTypeChange.emit(newAssistantType);
  }


  getStringType(typeString: string): AssistantType {
    switch (typeString) {
      case "JA": return AssistantType.Ja
      case "JA_F": return AssistantType.JaF
      case "SA": return AssistantType.Sa
      case "SA_F": return AssistantType.SaF
      case "SA_N": return AssistantType.SaNeo
      case "SA_FN": return AssistantType.SaFNeo
    }
    return AssistantType.Ja
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<form>
    <label class="text-sm" for="name"> Name </label>
    <input #assistantNameInput class="text-sm pl-2" id="name" [value]="assistantName"
        (change)="(assistantNameChanged(assistantNameInput.value))" placeholder="Jansen J" />

    <label class="text-sm mt-3" for="type"> Type </label>
    <select #assistantTypeInput class="text-sm pl-2" id="type" 
        (change)="(assistantTypeChanged(assistantTypeInput.value))">
        <option *ngFor="let type of assistantTypes" class="text-sm pl-2" value="type">
            <p class="text-sm">{{type}}</p>
        </option>
    </select>

</form>

// frontend/src/components/instance-input/NewAssistant.svelte
<script lang="typescript">
    
    import type { Assistant } from "../../openapi";
    import { AssistantType } from "../../openapi";

    export let assistant: Assistant

    const types: AssistantType[] = Object.values(AssistantType)


</script>

<form>
    <label class="text-sm" for="name"> Name </label>
    <input class="text-sm pl-2" id="name" bind:value={assistant.name} placeholder="Jansen J"/>

    <label class="text-sm mt-3" for="type"> Type </label>
    <select class="text-sm pl-2" id="type" bind:value={assistant.type}>
        {#each types as type}
            <option class="text-sm pl-2" value={type}><p class="text-sm">{type}</p></option>
        {/each}
    </select>

</form>
