// frontend/src/components/schedule-view/AssistantHeader.svelte
<script lang=typescript>

    import type { Assistant } from '../../openapi'
    
    export let assistant: Assistant
    export let workload: number
    export let max_workload: number
    export let min_workload: number

    function getWorkloadTextStyle() {
        if (workload == max_workload) {
            return "text-red-500 font-bold"
        } else if (workload == min_workload) {
            return "text-green-500 font-bold"
        } else {
            return "text-gray-700"
        }
    }
</script>


<div class="flex flex-row flex-none h-6 justify-between place-items-center cursor-default">
    <p class="{getWorkloadTextStyle()} text-xs"> {workload.toFixed(2)} </p>
    <p class="w-32 text-right text-black text-xs font-bold "> {assistant.name} </p>
</div>

// frontend2/src/app/schedule_view/assistant-header/assistant-header.component.ts
import { Component, Input, OnInit } from '@angular/core';


import type { Assistant } from 'build/openapi'
import { AssistantType } from 'build/openapi'

//export type assistantType =  AssistantType;


@Component({
  selector: 'app-assistant-header',
  templateUrl: './assistant-header.component.html',
  styleUrls: ['./assistant-header.component.css']
})
export class AssistantHeaderComponent implements OnInit {


  @Input()
  assistant: Assistant;

  @Input()
  workload: number;

  max_workload: number;
  min_workload: number;

  assistantType = AssistantType;
  

  getWorkloadTextStyle(): string {
    if (this.workload == this.max_workload) {
      return "text-red-500 font-bold"
    } else if (this.workload == this.min_workload) {
      return "text-green-500 font-bold"
    } else {
      return "text-gray-700"
    }
  }

  constructor() { }

  ngOnInit(): void {
    
  }

}

<div class="flex flex-row flex-none h-6 justify-between place-items-center align-center cursor-default">
    <div *ngIf="assistant.type == assistantType.Ja; else elseBlock1">
        <p class="text-xs mr-2">JA</p>
    </div>

    <ng-template #elseBlock1>
        <div *ngIf="assistant.type === assistantType.JaF; else elseBlock2">
            <p class="text-xs mr-2">JA_F</p>
        </div>
    </ng-template> 
        
    

    <ng-template #elseBlock2>
        <div *ngIf="assistant.type === assistantType.Sa; else elseBlock3">
            <p class="text-xs mr-2">SA</p>
        </div>
    </ng-template>

    <ng-template #elseBlock3>
        <div *ngIf="assistant.type === assistantType.SaF; else elseBlock4">
            <p class="text-xs mr-2">SA_F</p>
        </div>
    </ng-template>
        

    <ng-template #elseBlock4>
        <div *ngIf="assistant.type === assistantType.SaNeo; else elseBlock5">
            <p class="text-xs mr-2">SA_N</p>
        </div>
    </ng-template> 

    <ng-template #elseBlock5>
        <div *ngIf="assistant.type === assistantType.SaFNeo">
            <p class="text-xs mr-2">SA_FN</p>
        </div>
    </ng-template> 


    <p class="getWorkloadTextStyle() text-xs"> {{workload.toFixed(2)}} </p>
    <p class="w-24 text-right text-black text-xs font-bold "> {{assistant.name}} </p>

</div>
