// frontend/src/components/model-input/ModelInput.svelte
<script lang=typescript>
    
    import type { ModelParameters} from "../../openapi";
    
    import { Service } from '../../openapi';

    import Assignment from "../schedule-view/AssignmentBox.svelte";
    import Button from "./Button.svelte";
    import InputField from "./InputField.svelte";

    export let modelParams: ModelParameters

    function handleSubmit() {
        Service.postModelParams(modelParams)
    }

</script>

<main>
    <form class="flex flex-col"> 
        <p class="font-semibold text-sm cursor-default"> Model parameters </p>
        <p class="mt-4 font-semibold text-xs text-gray-500 cursor-default"> Minimum balance score </p>
        <InputField bind:value={modelParams.min_balance} step={1} />
        <p class="mt-4 font-semibold text-xs text-gray-500 cursor-default"> JAEV minimum balance </p>
        <InputField bind:value={modelParams.min_balance_jaev} step={1} />

        <p class="mt-4 font-semibold text-xs text-gray-500 cursor-default"> Workload + Max Buffer </p>
        <div class="flex flex-col space-y-2">
            {#each modelParams.shift_type_parameters as stp}
                <div class="flex flex-row space-x-1 items-center">
                    <Assignment assignment={{shift_type: stp.shift_type, part_of_min_balance:false, day_nb:0}}/>
                    <InputField bind:value={stp.shift_workload} step={0.01}/>
                    <InputField bind:value={stp.max_buffer} step={1}/>
                </div>
            {/each}
        </div>

        <div class="my-4 mx-auto">
            <Button callback={handleSubmit}> Submit </Button>
        </div>
    </form>

</main>

// frontend2/src/app/model_input/model-input/model-input.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

import type { ModelParameters} from "build/openapi";
  
import { DefaultService } from 'build/openapi';
import { Service } from 'build/openapi' // 
import { Observable } from 'rxjs';
//import { Assignment } from "../assignment-box/assignment-box.component"




@Component({
  selector: 'app-model-input',
  templateUrl: './model-input.component.html',
  styleUrls: ['./model-input.component.css'],
  providers: [ DefaultService, Service ]
})
export class ModelInputComponent implements OnInit {

  modelParameters: ModelParameters = {};
  
  buttonText: string = "Submit";
  constructor(private modelParamService: DefaultService) { }

  ngOnInit(): void {
    console.log("MODEL INPUT INITIALIZED")
    this.getModelParameters();
    console.log("model params: ", this.modelParameters)
  }

  // opgeroepen wanneer op button gedrukt wordt
  getValueChanged(evt: any, shift_type: string){
    if(typeof this.modelParameters.shift_type_parameters !== 'undefined'){
      for (const prms of this.modelParameters.shift_type_parameters){
        if(prms.shift_type == shift_type){
          prms.shift_workload = evt;
        }
      }
    }
    Service.postModelParams(this.modelParameters);
  }

  getValueBufferChanged(evt: any, shift_type: string){
    if(typeof this.modelParameters.shift_type_parameters !== 'undefined'){
      for (const prms of this.modelParameters.shift_type_parameters){
        if(prms.shift_type == shift_type){
          prms.max_buffer = evt;
        }
      }
    }
    Service.postModelParams(this.modelParameters);
  }


  handleSubmit(): void {
    console.log("HANDLE SUBMIT CALLED")
    console.log(this.modelParameters)
    Service.postModelParams(this.modelParameters);
  
  }

  balanceChanged(new_bal: number) {
      this.modelParameters.min_balance = new_bal
      this.handleSubmit()
  }
  balanceJaevChanged(new_bal: number) {
    this.modelParameters.min_balance_jaev = new_bal
    this.handleSubmit()
}


  // DIT IS AL NODIG OM GEEN UNDEFINED BODY TE KRIJGEN
  // TODO: MOMENTEEL 2X SUBMIT, NAAR 1 GAAN
  wrapSubmit(evt: any, shift_type: string): void {
    this.getValueChanged(evt, shift_type)
    //this.handleSubmit() // TODO: zien of dit nodig is?
  }


  getModelParameters(): void {
    this.modelParamService.modelParametersGetGet().subscribe( modelParameters => ( this.modelParameters = modelParameters));
  }
  

}

<form class="flex flex-col"> 
    <p class="font-semibold text-sm cursor-default"> Model parameters </p>
    <p class="mt-4 font-semibold text-xs text-gray-500 cursor-default"> Minimum balance score </p>
    <app-input-field [value]="modelParameters.min_balance" (onChange)="balanceChanged($event)" [step]="1"></app-input-field>
    <p class="mt-4 font-semibold text-xs text-gray-500 cursor-default"> JAEV minimum balance </p>
    <app-input-field [value]="modelParameters.min_balance_jaev" (onChange)="balanceJaevChanged($event)" [step]="1"></app-input-field>
    

    <p class="mt-4 font-semibold text-xs text-gray-500 cursor-default"> Workload + Max Buffer </p>
    <div class="flex flex-col space-y-2">


        <div *ngFor="let item of modelParameters.shift_type_parameters">  
                <div class="flex flex-row space-x-1 items-center">
                    
                    <app-assignment-box [assignment] = "{shift_type: item.shift_type, part_of_min_balance:false, day_nb:0}"></app-assignment-box>
                    <app-input-field [value]="item.shift_workload" (onChange)="wrapSubmit($event, item.shift_type)" [step]="1"></app-input-field>
                    <app-input-field [value]="item.max_buffer" (onChange)="getValueBufferChanged($event, item.shift_type)" [step]="1"></app-input-field>

                </div>
                
        </div>

    </div>

</form>
