// frontend2/src/app/schedule_view/day-header/day-header.component.ts
import { Component, Input, OnInit } from '@angular/core';

import type { Day } from 'build/openapi';




@Component({
  selector: 'app-day-header',
  templateUrl: './day-header.component.html',
  styleUrls: ['./day-header.component.css']
})
export class DayHeaderComponent implements OnInit {

  @Input()
  day: Day;


  day_of_week(day: Day): string {
    switch (day.id % 7) {
        case 0:
            return "Thu";
        case 1:
            return "Fri";
        case 2:
            return "Sat";
        case 3:
            return "Sun";
        case 4:
            return "Mon";
        case 5:
            return "Tue";
        case 6:
            return "Wed";
    }
    return "";
}


  constructor() { }

  ngOnInit(): void {
    //   console.log("INIT DAY HEADER")
      
  }

}

<div class="flex flex-col flex-none w-12 justify-center align-center place-items-center cursor-default">
    <div class="flex w-12 rounded justify-center">
        <p class="m-auto text-xs font-bold text-black"> {{day_of_week(day)}}</p>
    </div>
    <div *ngIf="day.is_holiday; else elseBlock"  class="flex w-12 rounded bg-yellow-200 justify-center  place-items-center ">
        <p class="m-auto text-xs font-bold text-black"> {{day.date.day + "/" + day.date.month}}</p>
    </div> 
    <ng-template #elseBlock>
        <div class="flex w-12 rounded justify-center align-center">
            <p class="m-auto text-xs font-bold text-black items-center align-center" style="text-align:right"> {{day.date.day + "/" + day.date.month}}</p>
        </div> 
    </ng-template>
</div>

// frontend/src/components/scheduleView/DayHeader.svelte
<script lang=typescript>

    export let day: number

    function getDay(dayNb: number): string {
        switch (dayNb % 7) {
            case 0:
                return "Thu";
            case 1:
                return "Fri";
            case 2:
                return "Sat";
            case 3:
                return "Sun";
            case 4:
                return "Mon";
            case 5:
                return "Tue";
            case 6:
                return "Wed";
        }
    }

</script>


<main>
    <div class="flex flex-col h-12 w-12 justify-end items-center cursor-default">
        {#if day % 7 == 1}
            <p class="text-xs font-bold text-black"> WEEK {(Math.floor(day/7) + 1)}</p>
        {/if}
        <p class="text-xs font-bold text-black"> {getDay(day)}</p>
    </div>
</main>
