// frontend/src/components/schedule-view/ScheduleView.svelte
<script lang=typescript>

    import type { Schedule, InstanceData, Assistant, IndividualSchedule } from '../../openapi';
    import { AssistantType } from '../../openapi';
    
    import AssistantHeader from './AssistantHeader.svelte'
    import DayHeader from './DayHeader.svelte';
    import AssignmentBox from './AssignmentBox.svelte';

    import { onMount } from 'svelte';

    export let schedule: Schedule;
    export let data: InstanceData;

    let max_workload = Math.max(...schedule.individual_schedules.map((a) => a.workload))
    let min_workload = Math.min(...schedule.individual_schedules.map((a) => a.workload))

    function getAssistant(id: number): Assistant {
        return data.assistants.find(a => a.id === id);
    }

    function getIs(id: number): IndividualSchedule {
        return schedule.individual_schedules.find(s => s.assistant_id === id);
    }

    const types: AssistantType[] = Object.values(AssistantType)

    onMount(async () => {
		let isSyncingLeftScroll: boolean = false;
        let isSyncingTopScroll: boolean = false;
        let isSyncingCenterScroll: boolean = false;
        let leftDiv: HTMLElement = document.getElementById('assistantlist');
        let topDiv: HTMLElement = document.getElementById('dayheaders');
        let centerDiv: HTMLElement = document.getElementById('schedule');

        leftDiv.onscroll = function() {
            if (!isSyncingLeftScroll) {
                isSyncingCenterScroll = true;
                centerDiv.scrollTop = leftDiv.scrollTop;
            }
            isSyncingLeftScroll = false;
        }

        topDiv.onscroll = function() {
            if (!isSyncingTopScroll) {
                isSyncingCenterScroll = true;
                centerDiv.scrollLeft = topDiv.scrollLeft;
            }
            isSyncingTopScroll = false;
        }

        centerDiv.onscroll = function() {
            if (!isSyncingCenterScroll) {
                isSyncingLeftScroll = true;
                isSyncingTopScroll = true;
                leftDiv.scrollTop = centerDiv.scrollTop;
                topDiv.scrollLeft = centerDiv.scrollLeft;
            }
            isSyncingCenterScroll = false;

        }
	});

</script>

<div class="flex flex-row space-x-10 justify-end w-full font-bold text-sm">
    <p> fairness score: {schedule.fairness_score.toFixed(2)} </p>
    <p> JAEV fairness score: {schedule.jaev_fairness_score.toFixed(2)} </p>
</div>

<div class="flex flex-row flex-nowrap space-x-2 w-full overflow-y-scroll">
    <div class="flex flex-col h-full">
        <div class="flex flex-none h-10"/> <!--placeholder-->
        <div id="assistantlist" class=" scrollbar-hidden flex flex-row overflow-y-scroll">
            <div  class="flex flex-none flex-col h-full space-y-1">
                {#each types as type}
                    {#each data.assistants.filter((a) => a.type == type) as assistant (assistant.id)}
                        <AssistantHeader {assistant} workload={getIs(assistant.id).workload} {max_workload} {min_workload}/>
                    {/each}
                {/each}
            </div>
        </div>
    </div>
    <div class="flex flex-col h-full overflow-scroll space-y-2">
        <div id="dayheaders" class="scrollbar-hidden flex flex-none flex-row overflow-x-scroll space-x-1">
            {#each data.days as day}
                <DayHeader {day}/>
                {#if day.id % 7 === 0}
                    <div class="flex flex-none w-4"/>
                {/if}
            {/each}
        </div>
        <div id="schedule" class="scrollable flex flex-col h-full w-full overflow-scroll space-y-1">
            {#each types as type}
                {#each data.assistants.filter((a) => a.type == type) as assistant (assistant.id)}
                    <div class="flex flex-row w-full space-x-1">
                        {#each data.days as day}
                            <AssignmentBox assignment={getIs(assistant.id).assignments.find(a => a.day_nb === day.id)} free_day={assistant.free_days.includes(day.id)}/>
                             {#if day.id % 7 === 0}
                                <div class="flex flex-none w-4"/>
                            {/if}
                        {/each}
                    </div>
                {/each}
            {/each}
        </div>
    </div>
</div>

// frontend2/src/app/schedule_view/schedule-view/schedule-view.component.ts
import { Component, OnInit } from '@angular/core';



import type { Schedule, InstanceData, Assistant, IndividualSchedule, Assignment, Day } from 'build/openapi';
import { AssistantType } from 'build/openapi';
import { DefaultService } from 'build/openapi';

import { AssistantHeaderComponent } from '../assistant-header/assistant-header.component';
import { DayHeaderComponent } from '../day-header/day-header.component';
import { AssignmentBoxComponent } from '../assignment-box/assignment-box.component';




@Component({
  selector: 'app-schedule-view',
  templateUrl: './schedule-view.component.html',
  styleUrls: ['./schedule-view.component.css']
})
export class ScheduleViewComponent implements OnInit {

  schedule?: Schedule = {
    fairness_score: 0,
    balance_score: 0,
    jaev_fairness_score: 0,
    jaev_balance_score: 0,
    individual_schedules: []
  };
  data: InstanceData = {
    assistants: [],
    days: []
  };

  
  workload_array = this.schedule?.individual_schedules?.map((a) => a.workload)

  max_workload?: number = this.workload_array?.reduce(function (a, b) {
    return Math.max(a, b);
  }, 0);

  min_workload?: number = this.workload_array?.reduce(function (a, b) {
    return Math.min(a, b);
  }, 0);


  types: AssistantType[] = Object.values(AssistantType)


  getAssistant(id: number): Assistant | undefined{
    return this.data.assistants.find(a => a.id === id);
  }

  getIs(id: number): IndividualSchedule | undefined {
    //console.log(this.schedule?.individual_schedules?.find(s => s.assistant_id === id))
    if(this.schedule?.individual_schedules?.find(s => s.assistant_id === id) == undefined){
      console.log("UNDEFINDED GET IS: ", id );
    }
    return this.schedule?.individual_schedules?.find(s => s.assistant_id === id);
  }

  getAssignmentsOnDay(assistant: Assistant, day: Day): Assignment | undefined { 
      return this.getIs(assistant.id).assignments.find(a => a.day_nb === day.id)
  }

  getInstanceInput(): void {
    
    this.instanceInputService.instanceDataGetGet().subscribe(data => (this.data = data));
    console.log("DATA ON GET= ", this.data)
  }

  getScheduleInput(): void {
    this.instanceInputService.dbScheduleGet().subscribe(schedule => (this.schedule = schedule));
  }

  constructor(private instanceInputService: DefaultService) { }

  ngOnInit(): void {

    console.log("Init Schedule View")
    console.log(this.types)
    this.getInstanceInput();
    this.getScheduleInput();

    let isSyncingLeftScroll: boolean = false;
    let isSyncingTopScroll: boolean = false;
    let isSyncingCenterScroll: boolean = false;
    let leftDiv: HTMLElement | null = document.getElementById('assistantlist');
    let topDiv: HTMLElement | null  = document.getElementById('dayheaders');
    let centerDiv: HTMLElement | null = document.getElementById('schedule');

    if(leftDiv !== null){
      leftDiv.onscroll = function () {
        if (!isSyncingLeftScroll && leftDiv !== null && centerDiv !== null) {
          isSyncingCenterScroll = true;
          centerDiv.scrollTop = leftDiv.scrollTop;
        }
        isSyncingLeftScroll = false;
      }
    }

    if(topDiv !== null){
      topDiv.onscroll = function () {
        if (!isSyncingTopScroll && centerDiv !== null && topDiv !== null) {
          isSyncingCenterScroll = true;
          centerDiv.scrollLeft = topDiv.scrollLeft;
        }
        isSyncingTopScroll = false;
      }
    }
    
    if(centerDiv !== null){
      centerDiv.onscroll = function () {
        if (!isSyncingCenterScroll && leftDiv !== null && topDiv !== null && centerDiv !== null) {
          isSyncingLeftScroll = true;
          isSyncingTopScroll = true;
          leftDiv.scrollTop = centerDiv.scrollTop;
          topDiv.scrollLeft = centerDiv.scrollLeft;
        }
        isSyncingCenterScroll = false;
  
      }
    }
  }

}


<div class="flex flex-row space-x-10 justify-end w-full font-bold text-sm">
    <p> fairness score: {{schedule.fairness_score.toFixed(2)}} </p>
    <p> JAEV fairness score: {{schedule.jaev_fairness_score.toFixed(2)}} </p>
</div>



<div class="flex flex-row flex-nowrap space-x-2 w-full ">
    <div class="flex flex-col h-full">
        <div class="flex flex-none h-20"></div> <!--placeholder-->
            <div id="assistantlist" class="scrollbar-hidden flex flex-row h-full overflow-y-scroll">
                <div class="flex flex-none flex-col h-full space-y-1">
                    
                    <div  *ngFor="let type of types">
                        
                        <div *ngFor="let assistant of data.assistants | assistantPipe : type">
                            
                            <app-assistant-header [assistant]="assistant" [workload]="getIs(assistant.id).workload"></app-assistant-header>
                        </div>  
                    </div>
                </div>
            </div>
        </div>   
        
    <div class="flex flex-col h-full overflow-scroll space-y-2">
        <div id="dayheaders" class="scrollbar-hidden flex flex-none flex-row overflow-x-scroll space-x-2">
            
            <div *ngFor="let day of data.days">
                <app-day-header [day]="day" > </app-day-header>
                <div *ngIf="day.id % 7 == 0">
                    <div class="flex flex-none w-16"></div>
                </div>
            </div>
            
        </div>
        <div id="schedule" class="scrollable flex flex-col h-full w-full overflow-x-scroll overflow-y-scroll space-y-1">
            <div *ngFor="let type of types">
                <div *ngFor="let assistant of data.assistants | assistantPipe : type">
                    <div class="flex flex-row w-full space-x-2">
                        <div *ngFor="let day of data.days">
                            <app-assignment-box [assignment]="getAssignmentsOnDay(assistant, day)" ></app-assignment-box>
                            <div *ngIf="day.id % 7 == 0" >
                           
                                <div class="flex flex-none w-16">
                                 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>


</div>
